name: tp2
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.3
  timelines: ^0.1.0
  qr_flutter: ^4.1.0
  http: ^0.13.5
  shared_preferences: 2.2.3
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.6
  timeline_tile: ^2.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/apple.png
    - assets/images/google.png
    - assets/images/facebook (1).png
    - assets/images/image-3.png
    - assets/images/image-4.png
    - assets/images/image-5.png
    - assets/images/dokter.png
    - assets/images/Berita.png
    - assets/images/perempuan.jpg
    - assets/images/dokter2.png
    - assets/images/banner.png
    - assets/images/hospital.png
    - assets/images/vegetable.jpg
    - assets/images/RS.png
    - assets/images/maps.png
    - assets/images/logo.png
    - assets/images/vc.png
    - assets/images/kesehatan.png
    - assets/images/jadwal.png
    - assets/images/fruit.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
